### ISSUE TITLE
Turbo-Props -- BYO Theme, we'll bring the Types

### ISSUE THREAD

**Issue by benschac** [react-native-nyc/meetup-talk-submissions#2]
## React Native NYC Talk Submission

**Talk Title:**
Turbo-Props -- BYO Theme, we'll bring the Types

**Talk Description:**
@stephenlaughton and I wrote a wrapper around styled-components which gives a nice developer experience layer on top of styled-components.

https://github.com/GarbageMountain/turbo-props
https://github.com/GarbageMountain/turbo-starter -- a link to the project & starter template

Additionally, it can support web too.
**Name**:

**Brief Bio (max 100 words):**

**Twitter Handle (optional)**:
benschac

**Comment by ilyausorov** [comment]
Hey @benschac , thank for submitting your talk proposal! This looks awesome, I'm a big fan of styled components and this looks like a great addition to using it. Would you want to present at the upcoming RN NYC meetup on Sep 15? We've got 1 speaking slot left.

**Comment by benschac** [comment]
LFG!! 🥲✨🚀 would it be possible to have the co-author of turbo video in too? He’s in Vancouver, not sure if he’s around but would be fun if we could do the talk together.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ilyausorov** [comment]
@benschac That may be tricky -- I don't know what the AV capabilities of the office where we'll doing the event are. We can investigate, but safest to plan to do it solo. Would you want to connect next week for a quick chat about the talk and the event?

**Comment by benschac** [comment]
Yeah, sounds great.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ilyausorov** [comment]
Can you grab a time from my [Calendly](https://calendly.com/ilya-boldvoice) thanks!
